from tkinter import *
import sqlite3

def create_tables():
	# tables = ['company', 'developer', 'APP', 'platform',
	# 		  'client', 'trade', 'report_bug']
	sqls = ['''CREATE TABLE COMPANY(
			COMPANY_ID CHAR(20) NOT NULL PRIMARY KEY,
   			COMPANY_NAME CHAR(20) NOT NULL,
   			IS_INTERNATIONAL CHAR(5) NOT NULL
		)''',
			'''CREATE TABLE DEVELOPER(
			DEVELOPER_ID CHAR(20) NOT NULL PRIMARY KEY,
   			POSITION CHAR(20) NOT NULL,
   			SALARY INT NOT NULL,
   			WORK_FOR_ID CHAR(20) NOT NULL,
   			FOREIGN KEY(WORK_FOR_ID) REFERENCES COMPANY(COMPANY_ID)
		)''',
			'''CREATE TABLE APP(
			APP_ID CHAR(20) NOT NULL PRIMARY KEY,
   			INSTALL_NUM INT NOT NULL,
   			COST INT NOT NULL,
   			RELEASE_ID CHAR(20) NOT NULL,
   			FOREIGN KEY(RELEASE_ID) REFERENCES COMPANY(COMPANY_ID)
		)''',
			'''CREATE TABLE PLATFORM(
			WEBSITE_IP CHAR(20) NOT NULL PRIMARY KEY,
   			POPULARITY INT NOT NULL,
   			TRADE_NUM INT NOT NULL
		)''',
			'''CREATE TABLE CLIENT(
			CLIENT_ID CHAR(20) NOT NULL PRIMARY KEY,
   			JOB CHAR(20) NOT NULL,
   			AGE INT NOT NULL
		)''',
			'''CREATE TABLE TRADE(
			TRADE_ID CHAR(20) NOT NULL PRIMARY KEY,
   			PLATFORM_ID CHAR(20) NOT NULL,
   			APP_ID CHAR(20) NOT NULL,
   			CLIENT_ID CHAR(20) NOT NULL,
   			FOREIGN KEY(PLATFORM_ID) REFERENCES PLATFORM(WEBSITE_IP),
   			FOREIGN KEY(APP_ID) REFERENCES APP(APP_ID),
   			FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
		)''',
			'''CREATE TABLE REPORT_BUG(
			BUG_ID CHAR(20) NOT NULL PRIMARY KEY,
   			DEVELOPER_ID CHAR(20),
   			APP_ID CHAR(20),
   			CLIENT_ID CHAR(20),
   			FOREIGN KEY(DEVELOPER_ID) REFERENCES DEVELOPER(DEVELOPER_ID),
   			FOREIGN KEY(APP_ID) REFERENCES APP(APP_ID),
   			FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
		)''']

	conn = sqlite3.connect('database.db')
	c = conn.cursor()
	c.execute('''PRAGMA foreign_keys = ON''')
	for s in sqls:
		c.execute(s)
	# c.execute('''PRAGMA foreign_keys = OFF''')
	conn.commit()
	conn.close()

	return

create_tables()